name: aosp
on:
  workflow_dispatch:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
    working-directory: $HOME

jobs:
  job_1:
    name: upload only 
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        run: |
          echo 111 > /tmp/hi
          pwd
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: /tmp/hi

  job_2:
    name: both download and upload
    needs: job_1
    runs-on: ubuntu-20.04
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: test
      - shell: bash
        run: |
          echo 2nd job >> test.txt
          ls -lah /tmp
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.txt

  job_3:
    name: download only
    needs: job_2
    runs-on: ubuntu-20.04
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: test
      - name: Print the final result
        shell: bash
        run: |
          echo bye
