name: aosp
on:
  workflow_dispatch:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
    working-directory: /home/runner

jobs:
  job_1:
    name: upload only 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Source all.sh
        run: |
          source all.sh
          ls
      - name: Source slim2
        run: |
          source slim2
      - name: Upload cache from job 1
        uses: actions/upload-artifact@v2
        with:
          name: cache
          path: /home/runner/all.sh

  job_2:
    name: both download and upload
    needs: job_1
    runs-on: ubuntu-20.04
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: test
      - shell: bash
        run: |
          echo 2nd job >> test.txt
          ls -lah /tmp
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.txt

  job_3:
    name: download only
    needs: job_2
    runs-on: ubuntu-20.04
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: test
      - name: Print the final result
        shell: bash
        run: |
          echo bye
